apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-notification-service-config
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.notificationServiceConfig.springProfilesActive
    | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-workflow-service-config
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  DATASOURCE_DRIVER: {{ .Values.workflowServiceConfig.datasourceDriver | quote }}
  DATASOURCE_PASSWORD: {{ .Values.workflowServiceConfig.datasourcePassword | quote
    }}
  DATASOURCE_URL: {{ .Values.workflowServiceConfig.datasourceUrl | quote }}
  DATASOURCE_USERNAME: {{ .Values.workflowServiceConfig.datasourceUsername | quote
    }}
  NOTIFICATION_SERVER_URL: {{ .Values.workflowServiceConfig.notificationServerUrl
    | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.workflowServiceConfig.springProfilesActive |
    quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-ldif-config-td2h4849h2
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  test-server.ldif: {{ .Values.ldifConfigTd2H4849H2.testServerLdif | toYaml | indent
    1 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-postgres-service-config
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgresServiceConfig.postgresDb | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresServiceConfig.postgresPassword | quote }}
  POSTGRES_USER: {{ .Values.postgresServiceConfig.postgresUser | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-ldap
  labels:
    app: ldap-service
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ldap.type }}
  selector:
    app: ldap-service
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.ldap.ports | toYaml | nindent 2 -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-notification-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.notificationService.type }}
  selector:
    app: notification-service
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.notificationService.ports | toYaml | nindent 2 -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-postgres
  labels:
    app: postgres-service
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.type }}
  selector:
    app: postgres-service
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.postgres.ports | toYaml | nindent 2 -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-workflow-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.workflowService.type }}
  selector:
    app: workflow-service
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.workflowService.ports | toYaml | nindent 2 -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-ldap-deployment
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: ldap-service
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: ldap-service
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args: {{- toYaml .Values.ldapDeployment.ldapService.args | nindent 8 }}
        env:
        - name: LDAP_PORT
          value: {{ quote .Values.ldapDeployment.ldapService.env.ldapPort }}
        - name: LDAP_SEED_INTERNAL_LDIF_PATH
          value: {{ quote .Values.ldapDeployment.ldapService.env.ldapSeedInternalLdifPath
            }}
        - name: SPRING_PROFILES_ACTIVE
          value: {{ quote .Values.ldapDeployment.ldapService.env.springProfilesActive }}
        - name: LDAP_LOG_LEVEL
          value: {{ quote .Values.ldapDeployment.ldapService.env.ldapLogLevel }}
        - name: LDAP_ORGANISATION
          value: {{ quote .Values.ldapDeployment.ldapService.env.ldapOrganisation }}
        - name: LDAP_DOMAIN
          value: {{ quote .Values.ldapDeployment.ldapService.env.ldapDomain }}
        - name: LDAP_BASE_DN
          value: {{ quote .Values.ldapDeployment.ldapService.env.ldapBaseDn }}
        - name: LDAP_ADMIN_PASSWORD
          value: {{ quote .Values.ldapDeployment.ldapService.env.ldapAdminPassword }}
        - name: LDAP_CONFIG_PASSWORD
          value: {{ quote .Values.ldapDeployment.ldapService.env.ldapConfigPassword }}
        - name: LDAP_TLS_CRT_FILENAME
          value: {{ quote .Values.ldapDeployment.ldapService.env.ldapTlsCrtFilename }}
        - name: LDAP_TLS_KEY_FILENAME
          value: {{ quote .Values.ldapDeployment.ldapService.env.ldapTlsKeyFilename }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.ldapDeployment.ldapService.image.repository }}:{{ .Values.ldapDeployment.ldapService.image.tag
          | default .Chart.AppVersion }}
        name: ldap-service
        ports:
        - containerPort: 389
          name: ldap-insecure
        resources: {}
        volumeMounts:
        - mountPath: /ldif/
          name: ldif-volume
      volumes:
      - configMap:
          name: {{ include "chart.fullname" . }}-ldif-config-td2h4849h2
        name: ldif-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-notification-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: notification-service
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: notification-service
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "chart.fullname" . }}-notification-service-config
        image: {{ .Values.notificationService.notificationService.image.repository }}:{{
          .Values.notificationService.notificationService.image.tag | default .Chart.AppVersion
          }}
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 4
        name: notification-service
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 4
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-postgres-deployment
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: postgres-service
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: postgres-service
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "chart.fullname" . }}-postgres-service-config
        image: {{ .Values.postgresDeployment.postgresService.image.repository }}:{{ .Values.postgresDeployment.postgresService.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          exec:
            command:
            - pg_isready
          initialDelaySeconds: 15
          timeoutSeconds: 2
        name: postgres-service
        ports:
        - containerPort: 5432
          name: insecure
        readinessProbe:
          exec:
            command:
            - pg_isready
          initialDelaySeconds: 15
          timeoutSeconds: 2
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-workflow-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: workflow-service
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: workflow-service
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "chart.fullname" . }}-workflow-service-config
        image: {{ .Values.workflowService.workflowService.image.repository }}:{{ .Values.workflowService.workflowService.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.workflowService.workflowService.imagePullPolicy }}
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 4
        name: workflow-service
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 25
          timeoutSeconds: 4
        resources: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-notification-ingress
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  rules:
  - host: notification-service.parodos-dev
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-notification-service'
            port:
              number: 8080
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-workflow-ingress
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  rules:
  - host: workflow-service.parodos-dev
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-workflow-service'
            port:
              number: 8080
        path: /
        pathType: Prefix