apiVersion: v1
kind: Service
metadata:
  name: {{ include "parodos-v1.0.18.fullname" . }}-backstage
  labels:
  {{- include "parodos-v1.0.18.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backstage.type }}
  selector:
    app: backstage
  {{- include "parodos-v1.0.18.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.backstage.ports | toYaml | nindent 2 -}}