apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "parodos-testing.fullname" . }}-workflow-ingress
  labels:
  {{- include "parodos-testing.labels" . | nindent 4 }}
spec:
  rules:
  - host: workflow-service.parodos-dev
    http:
      paths:
      - backend:
          service:
            name: '{{ include "parodos-testing.fullname" . }}-workflow-service'
            port:
              number: 8080
        path: /
        pathType: Prefix