apiVersion: charts.redhat.com/v1alpha1
kind: Parodos
metadata:
  name: parodos-sample
spec:
  # Default values copied from <project_dir>/helm-charts/parodos-v.1.0.18/values.yaml
  kubernetesClusterDomain: cluster.local
  
  
