# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/charts.redhat.com_parodos.yaml
- bases/charts.redhat.com_parodosv1018s.yaml
#+kubebuilder:scaffold:crdkustomizeresource
